-- MySQL Script generated by MySQL Workbench
-- Adaptado para phpMyAdmin
-- Data: 2025-08-23

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgst_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sgst_bd` ;
CREATE SCHEMA IF NOT EXISTS `sgst_bd` DEFAULT CHARACTER SET utf8 ;
USE `sgst_bd` ;


-- -----------------------------------------------------
-- Table `status_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `status_turma` ;
CREATE TABLE IF NOT EXISTS `status_turma` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `nome_status` VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (`id_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `status_turma`
INSERT INTO status_turma (nome_status) VALUES
('Planejada'),
('Confirmada'),
('Em Andamento'),
('Concluída'),
('Cancelada');


-- -----------------------------------------------------
-- Table `turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turno` ;
CREATE TABLE IF NOT EXISTS `turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `nome_turno` VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (`id_turno`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `turno`
INSERT INTO turno (nome_turno) VALUES
('Matutino'),
('Vespertino'),
('Noturno'),
('Integral');

-- -----------------------------------------------------
-- Table `tipo_feriado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_feriado` ;
CREATE TABLE IF NOT EXISTS `tipo_feriado` (
  `id_tipo_feriado` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(50) NOT NULL UNIQUE,
  PRIMARY KEY (`id_tipo_feriado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `tipo_feriado`
INSERT INTO tipo_feriado (nome_tipo) VALUES
('feriado'),
('recesso');

-- -----------------------------------------------------
-- Table `tipos_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_sala` ;
CREATE TABLE IF NOT EXISTS `tipos_sala` (
  `idTipo_sala` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(100) NOT NULL UNIQUE,
  PRIMARY KEY (`idTipo_sala`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `tipos_sala`
INSERT INTO tipos_sala (nome_tipo) VALUES
('Sala de aula Inovadora'),
('Laboratório de TI'),
('Laboratório de Moda'),
('Laboratório de Imagem Pessoal'),
('Auditório'),
('Laboratório Multiuso'),
('Laboratório de Gastronomia');

-- -----------------------------------------------------
-- Table `salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salas` ;
CREATE TABLE IF NOT EXISTS `salas` (
  `id_salas` INT NOT NULL AUTO_INCREMENT,
  `nome_sala` VARCHAR(100) NOT NULL,
  `capacidade_maxima` INT NOT NULL,
  `idTipo_sala` INT,
  `local` VARCHAR(255),
  `recursos_especiais` TEXT,
  PRIMARY KEY (`id_salas`),
  CONSTRAINT `fk_sala_tipo`
    FOREIGN KEY (`idTipo_sala`) REFERENCES `tipos_sala` (`idTipo_sala`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `salas`
INSERT INTO salas (nome_sala, capacidade_maxima, idTipo_sala, local, recursos_especiais) VALUES
('Inovadora 1', 30, 1, 'Cep Talal Abu Allan', '1º Andar, carteiras universitárias, TV ou projetor, lousa digital ou quadro branco, acesso à internet, tomadas, iluminação adequada, climatização, espaço para dinâmicas, decoração moderna, recursos multimídia, ambiente colaborativo'),
('Inovadora 2', 20, 1, 'Cep Talal Abu Allan', '2º Andar, mesas móveis trapézio, TV ou projetor, lousa digital ou quadro branco, internet, tomadas, iluminação adequada, climatização, espaço para dinâmicas, decoração moderna, recursos multimídia, ambiente colaborativo'),
('Inovadora 3', 35, 1, 'Cep Talal Abu Allan', '2º Andar, carteiras universitárias, TV ou projetor, lousa digital ou quadro branco, internet, tomadas, iluminação adequada, climatização, recursos multimídia, ambiente colaborativo'),
('Inovadora 4', 33, 1, 'Cep Talal Abu Allan', '2º Andar, carteiras universitárias, TV ou projetor, lousa digital ou quadro branco, internet, tomadas, iluminação adequada, climatização, recursos multimídia, ambiente colaborativo'),
('Inovadora 5', 20, 1, 'Cep Talal Abu Allan', '2º Andar, mesas móveis trapézio, TV ou projetor, internet, tomadas, iluminação adequada, climatização, recursos multimídia, ambiente colaborativo'),
('Inovadora 6', 32, 1, 'Cep Talal Abu Allan', '2º Andar, carteiras universitárias, TV ou projetor, lousa digital ou quadro branco, internet, tomadas, iluminação adequada, climatização, recursos multimídia, ambiente colaborativo'),
('Técnico de Sistemas e Rede 1', 28, 2, 'Cep Talal Abu Allan', 'rack de rede com patch panels, switches gerenciáveis, cabeamento estruturado, roteadores, 30 computadores, servidor, projetor multimídia/TV interativa, nobreak, ferramentas de crimpagem, software de simulação'),
('Técnico de Sistemas e Rede 2', 28, 2, 'Cep Talal Abu Allan', 'rack de rede com patch panels, switches gerenciáveis, cabeamento estruturado, roteadores, 30 computadores, servidor, projetor multimídia/TV interativa, nobreak, ferramentas de crimpagem, software de simulação'),
('Técnico de Sistemas', 30, 2, 'Cep Talal Abu Allan', '30 computadores, servidor local, projetor multimídia/TV interativa, softwares de programação, banco de dados, virtualização, nobreak'),
('Produção de Moda', 20, 3, 'Cep Talal Abu Allan', 'máquinas de costura domésticas e industriais, overlock, mesa de corte grande, manequins, ferro, iluminação, armários de tecidos, kits de modelagem'),
('Imagem - Cabelos', 18, 4, 'Cep Talal Abu Allan', 'cadeiras de cabeleireiro, lavatórios água quente/fria, espelhos, secadores, chapinhas, iluminação frontal, tomadas distribuídas, esterilizadores'),
('Imagem - Estética e Unhas', 16, 4, 'Cep Talal Abu Allan', 'macas reclináveis, mesas de manicure com iluminação, esterilizadores, aparelhos de estética (alta frequência, vaporizador), poltronas pedicure, lavabos'),
('Imagem - Maquiagem e Produção', 14, 4, 'Cep Talal Abu Allan', 'cadeiras de maquiagem, bancadas com espelhos grandes, iluminação camarim 5000K, tomadas próximas, kits de pincéis, carrinhos auxiliares'),
('Auditório', 70, 5, 'Cep Talal Abu Allan', 'projetor, som, 2 ar-condicionados, 70 cadeiras, iluminação adequada, climatização, espaço para apresentações'),
('Técnico de Sistemas 1', 30, 2, 'Polo Recanto da Emas', 'computadores, servidor local, projetor multimídia/TV interativa, softwares de programação, banco de dados, virtualização, nobreak'),
('Técnico de Sistemas 2', 30, 2, 'Polo Recanto da Emas', 'computadores, servidor local, projetor multimídia/TV interativa, softwares de programação, banco de dados, virtualização, nobreak'),
('Multiuso de Cabelo, Unhas e Moda', 16, 6, 'Polo Recanto da Emas', 'provador, overlok, máquina de costura, secador, lockers, TV 85", bancadas, espelhos, cadeiras, lavatórios, iluminação estética, armários baixos, pontos de energia');


-- -----------------------------------------------------
-- Table `cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursos` ;
CREATE TABLE IF NOT EXISTS `cursos` (
  `id_cursos` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(255) NOT NULL UNIQUE,
  `segmento` VARCHAR(100) NOT NULL,
  `modalidade` ENUM('Presencial','EaD','Híbrido') DEFAULT 'Presencial',
  `carga_horaria` INT NOT NULL,
  `valor` DECIMAL(10,2) DEFAULT 0.00,
  `curso_tem` TINYINT(1) DEFAULT 0, 
  `bolsa_compativel` TINYINT(1) DEFAULT 1,
  `idTipo_sala` INT,
  PRIMARY KEY (`id_cursos`),
  CONSTRAINT `fk_curso_tipo`
    FOREIGN KEY (`idTipo_sala`) REFERENCES `tipos_sala` (`idTipo_sala`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `cursos`
INSERT INTO cursos (nome_curso, segmento, modalidade, carga_horaria, valor, curso_tem, bolsa_compativel, idTipo_sala) VALUES
('Fotografia de propaganda e publicidade', 'Comunicação', 'Presencial', 72, 800.00, 0, 1, 1),
('Fotografia Jornalística e Documental', 'Comunicação', 'Presencial', 72, 750.00, 0, 1, 1),
('Fotógrafo', 'Comunicação', 'Presencial', 190, 1500.00, 0, 1, 1),
('Produção de Vídeo para Internet', 'Comunicação', 'Presencial', 36, 600.00, 0, 1, 1),
('Técnico em Produção Cultural', 'Comunicação', 'Presencial', 800, 3500.00, 1, 1, 1),
('Aperfeiçoamento de Corte de Cabelo e Escova', 'Beleza', 'Presencial', 60, 900.00, 0, 1, 4),
('Beleza de Milhões', 'Beleza', 'Presencial', 100, 1200.00, 0, 1, 4),
('Colorimetria Avançada Aplicada a Cabeleireiros e Barbeiros', 'Beleza', 'Presencial', 100, 1300.00, 0, 1, 4),
('Colorimetria Capilar: Noções Básicas', 'Beleza', 'Presencial', 40, 700.00, 0, 1, 4),
('Construção de Carreira para Profissionais da Beleza', 'Beleza', 'EaD', 36, 500.00, 0, 1, 4),
('Design de Barba', 'Beleza', 'Presencial', 40, 800.00, 0, 1, 4),
('Design de Corte Feminino: Técnicas Avançadas', 'Beleza', 'Presencial', 72, 1000.00, 0, 1, 4),
('Design de Mechas', 'Beleza', 'Presencial', 40, 850.00, 0, 1, 4),
('Design de Sobrancelhas', 'Beleza', 'Presencial', 60, 700.00, 0, 1, 4),
('Extensão de Cílios: Fio a Fio', 'Beleza', 'Presencial', 20, 500.00, 0, 1, 4),
('Extensão de Cílios: Volume Russo', 'Beleza', 'Presencial', 20, 600.00, 0, 1, 4),
('Lash lifting e Brow lamination', 'Beleza', 'Presencial', 20, 550.00, 0, 1, 4),
('Maquiagem Profissional Avançada', 'Beleza', 'Presencial', 60, 900.00, 0, 1, 4),
('Microblading Fio a Fio', 'Beleza', 'Presencial', 60, 1500.00, 0, 1, 4),
('Micropigmentação', 'Beleza', 'Presencial', 80, 2000.00, 0, 1, 4),
('Penteados Avançados', 'Beleza', 'Presencial', 40, 700.00, 0, 1, 4),
('Penteados e Corte de Cabelos Afro', 'Beleza', 'Presencial', 40, 750.00, 0, 1, 4),
('Práticas de Trabalho do Cabeleireiro', 'Beleza', 'Presencial', 100, 1300.00, 0, 1, 4),
('Técnicas de Barbeiro', 'Beleza', 'Presencial', 80, 1000.00, 0, 1, 4),
('Técnicas de Depilação', 'Beleza', 'Presencial', 80, 900.00, 0, 1, 4),
('Tratamento Capilar', 'Beleza', 'Presencial', 40, 800.00, 0, 1, 4),
('Unhas Perfeitas: Manicure e Pedicure', 'Beleza', 'Presencial', 100, 1200.00, 0, 1, 4),
('A Arte de se Comunicar e de Vender Mais', 'Comunicação', 'EaD', 30, 400.00, 0, 1, 1),
('Copywriting: Redação Web para Marketing e Vendas', 'Comunicação', 'EaD', 36, 500.00, 0, 1, 1),
('Operador de áudio', 'Comunicação', 'Presencial', 208, 1800.00, 0, 1, 2),
('Práticas de DJ', 'Comunicação', 'Presencial', 48, 600.00, 0, 1, 2),
('Produção de podcast em vídeo', 'Comunicação', 'Presencial', 40, 700.00, 0, 1, 2),
('Storytelling para Marcas e Produtos', 'Comunicação', 'EaD', 42, 500.00, 0, 1, 1),
('Técnico em Multimídia', 'Comunicação', 'Presencial', 800, 3800.00, 1, 1, 2),
('Assistente de Secretaria Escolar', 'Educação', 'Presencial', 180, 900.00, 0, 1, 1),
('Inclusão de Pessoas com Deficiência', 'Educação', 'EaD', 36, 400.00, 0, 1, 1),
('Técnico em Secretaria Escolar', 'Educação', 'Presencial', 800, 3500.00, 1, 1, 1),
('Organizador de Eventos', 'Eventos', 'Presencial', 180, 1000.00, 0, 1, 1),
('Produção e Coordenação de Projetos de Cenografia', 'Eventos', 'Presencial', 36, 500.00, 0, 1, 1),
('Projetos de Cenografia para Shows', 'Eventos', 'Presencial', 48, 600.00, 0, 1, 1),
('Recepcionista de Eventos', 'Eventos', 'Presencial', 160, 800.00, 0, 1, 1),
('Técnico em Eventos', 'Eventos', 'Presencial', 800, 3600.00, 1, 1, 1),
('Açougueiro', 'Gastronomia', 'Presencial', 160, 1000.00, 0, 1, 7),
('Auxiliar de Cozinha', 'Gastronomia', 'Presencial', 240, 1200.00, 0, 1, 7),
('Auxiliar de Garçom (Cumim)', 'Gastronomia', 'Presencial', 160, 800.00, 0, 1, 7),
('Auxiliar de Padeiro', 'Gastronomia', 'Presencial', 180, 1000.00, 0, 1, 7),
('Barista', 'Gastronomia', 'Presencial', 160, 1200.00, 0, 1, 7),
('Bartender', 'Gastronomia', 'Presencial', 200, 1500.00, 0, 1, 7),
('Cake design - Aperfeiçoamento', 'Gastronomia', 'Presencial', 40, 600.00, 0, 1, 7),
('Confeiteiro', 'Gastronomia', 'Presencial', 300, 1800.00, 0, 1, 7),
('Cozinheiro', 'Gastronomia', 'Híbrido', 500, 2500.00, 0, 1, 7),
('Garçom', 'Gastronomia', 'Presencial', 240, 1000.00, 0, 1, 7),
('Padeiro', 'Gastronomia', 'Presencial', 260, 1400.00, 0, 1, 7),
('Pizzaiolo', 'Gastronomia', 'Presencial', 160, 1000.00, 0, 1, 7),
('Salgadeiro', 'Gastronomia', 'Presencial', 160, 1000.00, 0, 1, 7),
('Sommelier de Vinho', 'Gastronomia', 'Presencial', 144, 1500.00, 0, 1, 7),
('Sushiman', 'Gastronomia', 'Presencial', 160, 2000.00, 0, 1, 7),
('Técnico em Gastronomia', 'Gastronomia', 'Presencial', 800, 4200.00, 1, 0, 7),
('Assistente Administrativo', 'Gestão', 'EaD', 160, 800.00, 0, 1, 1),
('Assistente de Contabilidade', 'Gestão', 'EaD', 160, 850.00, 0, 1, 1),
('Assistente de Crédito e Cobrança', 'Gestão', 'EaD', 160, 850.00, 0, 1, 1),
('Assistente de Logística', 'Gestão', 'EaD', 160, 900.00, 0, 1, 1),
('Assistente de Marketing e Vendas', 'Gestão', 'EaD', 160, 900.00, 0, 1, 1),
('Assistente de Pessoal', 'Gestão', 'EaD', 160, 900.00, 0, 1, 1),
('Assistente de Recursos Humanos', 'Gestão', 'EaD', 160, 900.00, 0, 1, 1),
('Assistente Financeiro', 'Gestão', 'EaD', 160, 900.00, 0, 1, 1),
('Recepcionista', 'Gestão', 'Presencial', 160, 800.00, 0, 1, 1),
('Técnico em Administração', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Técnico em Contabilidade', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Técnico em Finanças', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Técnico em Logística', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Técnico em Marketing', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Técnico em Recursos Humanos', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Técnico em Secretariado', 'Gestão', 'Presencial', 800, 3200.00, 1, 1, 1),
('Camareiro em Meios de Hospedagem', 'Gestão', 'Presencial', 160, 800.00, 0, 1, 1),
('Recepcionista em Meios de Hospedagem', 'Gestão', 'Presencial', 160, 800.00, 0, 1, 1),
('Ajustes e Reformas do Vestuário', 'Moda', 'Presencial', 40, 600.00, 0, 1, 3),
('Análise de Coloração Pessoal', 'Moda', 'Presencial', 40, 700.00, 0, 1, 3),
('Branding e Marketing de Moda', 'Moda', 'EaD', 60, 800.00, 0, 1, 3),
('Consultoria de Estilo - Personal Stylist', 'Moda', 'Presencial', 60, 1000.00, 0, 1, 3),
('Consultoria de Imagem', 'Moda', 'Presencial', 160, 1200.00, 0, 1, 3),
('Costura Criativa', 'Moda', 'Presencial', 80, 1000.00, 0, 1, 3),
('Costura Prática e Moda Criativa', 'Moda', 'Presencial', 100, 1200.00, 0, 1, 3),
('Desenho de Moda Digital', 'Moda', 'Híbrido', 95, 1000.00, 0, 1, 3),
('Estamparia - Design de Superfície', 'Moda', 'Presencial', 80, 1000.00, 0, 1, 3),
('Moda Pet', 'Moda', 'Presencial', 40, 600.00, 0, 1, 3),
('Modelagem de Alfaiataria Feminina', 'Moda', 'Presencial', 100, 1200.00, 0, 1, 3),
('Modelagem para Corset', 'Moda', 'Presencial', 80, 1100.00, 0, 1, 3),
('Modelista', 'Moda', 'Presencial', 210, 2000.00, 0, 1, 3),
('Moulage', 'Moda', 'Presencial', 80, 1100.00, 0, 1, 3),
('Técnico em Produção de Moda', 'Moda', 'Presencial', 800, 4000.00, 1, 1, 3),
('Vitrinismo e Visual Merchandising para o Varejo de Moda', 'Moda', 'Presencial', 108, 1200.00, 0, 1, 3),
('Administrador de Redes', 'Tecnologia da Informação', 'Presencial', 200, 2000.00, 0, 1, 2),
('Arquitetura de Sistemas Cloud Computing', 'Tecnologia da Informação', 'EaD', 30, 400.00, 0, 1, 2),
('Assistente de Tecnologias da Informação', 'Tecnologia da Informação', 'Presencial', 200, 1500.00, 0, 1, 2),
('AutoCAD - Desenho de Ambientes em 2D', 'Tecnologia da Informação', 'Presencial', 60, 800.00, 0, 1, 2),
('Cloud computing - Gerenciamento de Serviços em nuvem', 'Tecnologia da Informação', 'EaD', 100, 900.00, 0, 1, 2),
('Construção de Websites com PHP e MySQL', 'Tecnologia da Informação', 'Presencial', 60, 1000.00, 0, 1, 2),
('Desenvolvedor Front-End', 'Tecnologia da Informação', 'Presencial', 264, 2500.00, 0, 1, 2),
('Desenvolvimento de Aplicativos Móveis', 'Tecnologia da Informação', 'Presencial', 100, 1500.00, 0, 1, 2),
('Editor de Projeto Visual Gráfico', 'Tecnologia da Informação', 'Presencial', 160, 1500.00, 0, 1, 2),
('Excel Com VBA e Dashboard', 'Tecnologia da Informação', 'EaD', 60, 700.00, 0, 1, 2),
('Formação - programação Python', 'Tecnologia da Informação', 'Presencial', 156, 1600.00, 0, 1, 2),
('Front-End: Html, Css, Bootstrap, js e Jquery', 'Tecnologia da Informação', 'Presencial', 100, 1200.00, 0, 1, 2),
('Implementar protocolos de rede em roteadores e switches', 'Tecnologia da Informação', 'Presencial', 96, 1100.00, 0, 1, 2),
('Informática Básica', 'Tecnologia da Informação', 'EaD', 20, 200.00, 0, 1, 2),
('Informática para Melhor Idade', 'Tecnologia da Informação', 'EaD', 100, 400.00, 0, 1, 2),
('Informática Windows e Office Fundamental', 'Tecnologia da Informação', 'Presencial', 100, 800.00, 0, 1, 2),
('Inteligência Artificial - Como Fazer a Pergunta Correta', 'Tecnologia da Informação', 'EaD', 20, 300.00, 0, 1, 2),
('Introdução à Programação com Lógica de Programação', 'Tecnologia da Informação', 'EaD', 60, 600.00, 0, 1, 2),
('Java - Programação Orientada a Objetos', 'Tecnologia da Informação', 'Presencial', 160, 1500.00, 0, 1, 2),
('Lógica de Programação e Algoritmos', 'Tecnologia da Informação', 'Presencial', 100, 900.00, 0, 1, 2),
('Montagem e Manutenção de Computadores', 'Tecnologia da Informação', 'Presencial', 160, 1200.00, 0, 1, 2),
('Redes de Computadores', 'Tecnologia da Informação', 'Presencial', 200, 1800.00, 0, 1, 2),
('Segurança da Informação e Proteção de Dados', 'Tecnologia da Informação', 'EaD', 60, 700.00, 0, 1, 2),
('Técnico em Informática', 'Tecnologia da Informação', 'Presencial', 800, 3500.00, 1, 1, 2),
('Técnico em Redes de Computadores', 'Tecnologia da Informação', 'Presencial', 800, 3500.00, 1, 1, 2),
('Web Designer - Criação e Desenvolvimento de Sites', 'Tecnologia da Informação', 'Presencial', 200, 2000.00, 0, 1, 2);


-- -----------------------------------------------------
-- Table `instrutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instrutores` ;
CREATE TABLE IF NOT EXISTS `instrutores` (
  `id_instrutores` INT NOT NULL AUTO_INCREMENT,
  `nome_instrutor` VARCHAR(100) NOT NULL UNIQUE,
  `segmento_principal` VARCHAR(100),
  `habilidades_extras` TEXT,
  PRIMARY KEY (`id_instrutores`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `instrutores`
INSERT INTO instrutores (nome_instrutor, segmento_principal) VALUES
('Adailton Rodrigues Duarte', 'Educacional'),
('Michelle Pereira Soares', 'Educacional'),
('Ismael Alves Gomes', 'Gastronomia'),
('Isabela Mayane Diniz Mota', 'Gastronomia'),
('Ana Lúcia Feitosa', 'Gastronomia'),
('Joseny Juvito De Souza', 'Gastronomia'),
('Anna Paula Caribe Schwam', 'Gastronomia'),
('Victor Hugo Alves Xavier', 'Gastronomia'),
('Marcos Antonio Facanha Da Silva Junior', 'Gastronomia'),
('Joyce Santos Brum', 'Gastronomia'),
('Kelly Alves De Oliveira', 'Gestão'),
('Luzineide Maria De Araujo', 'Gestão'),
('Elisangela Machado Da Silva Gomes', 'Gestão'),
('Liliane Cavalcante De Oliveira', 'Gestão'),
('Patrícia Barbosa Alves De Almeida', 'Gestão'),
('Elisa Rosa Coimbras', 'Gestão'),
('Lúcio Alexandre Souza Lordes', 'Gestão'),
('Ricardo Da Silva Pierre', 'Gestão'),
('Wender Freitas Reis', 'Gestão'),
('Edson Luiz Cabral Dos Santos', 'Gestão'),
('Jefferson Soares Teixeira Alves', 'Gestão'),
('Jonas Aparecido Dias', 'Gestão'),
('Francisco Edivan Da Silva', 'Gestão'),
('Nara Moura De Sena', 'Gestão'),
('Joelma Aparecida Leite', 'Gestão'),
('Luís Fernando Portela De Faria', 'Gestão'),
('Geane Pinto Camargo', 'Gestão'),
('Alessandra Antonia Pereira', 'Gestão'),
('Aline Correa Lopes', 'Gestão'),
('Luanna Alves De Oliveira Farias Belloti', 'Gestão'),
('Analice Barbosa Santos De Oliveira', 'Gestão'),
('Katyara Pinheiro Sousa Cunha', 'Gestão'),
('Lindomar Silva Bastos', 'Gestão'),
('Cleia Dos Santos Rohod', 'Gestão'),
('Alexandre Humberto Bessa Ferreira', 'Gestão'),
('Jose De Assis Custodio', 'Gestão'),
('Franklin George Andrade Batista', 'Gestão'),
('Dionisio Francisco Pereira', 'Gestão'),
('Marileia De Jesus Amorim', 'Gestão'),
('Giorgia Barreto Lima Parriao', 'Gestão'),
('Aldemir Rodrigues Martins', 'Gestão'),
('Ana Claudia Lima Soares', 'Gestão'),
('Joarisvaldo Queiroz Martins', 'Gestão'),
('Petrick De Oliveira Tomasini', 'Gestão'),
('Ricardo Pereira Gomes De Araujo', 'Gestão'),
('Miracleia Almeida De Lima Castro', 'Gestão'),
('Bianca Gabriel Fellet', 'Gestão'),
('Juliana Holanda Nogueira Peixoto Cortez', 'Gestão'),
('Jose Pericles Freire Barroncas', 'Gestão'),
('Thalita Barboza Rocha Cardoso', 'Gestão'),
('Ronia Pinheiro Marra De Sousa', 'Gestão'),
('Marcela Nunes Mesquita Ribas Lopes Dos Santos', 'Gestão'),
('Israel Vila Verde Belem', 'Gestão'),
('Flavio Pereira De Sousa', 'Gestão'),
('Kedna Medeiros Dos Santos', 'Gestão'),
('Sandro Tibirica Dos Santos Carneiro', 'Gestão'),
('Marcela Rocha Mendonca Ribeiro', 'Gestão'),
('Paulo Cesar Pereira Soares', 'Gestão'),
('Rosivane Machado Cavalcante Monteiro', 'Gestão'),
('Mauricio Pereira Barroso Dos Santos', 'Gestão'),
('Debora Raquel De Macedo Carinhanha', 'Idiomas'),
('Maria Cristina Gomes De Oliveira', 'Moda'),
('Tatiane Silva Dos Santos', 'Moda'),
('Maria De Fátima Reis Lima Silva', 'Moda'),
('Erenita Vieira Tolentino', 'Moda'),
('Ilcimara Belo Barbosa Correia Viana', 'Moda'),
('Bianca Mendes Da Silva', 'Moda'),
('Suely De Fatima Pereira', 'Moda'),
('Keyla Beatriz Pires', 'Moda'),
('Maria Zenaide Peixoto Cavalcante', 'Produção de Alimentos'),
('Waldemar Camilo Ferreira', 'Produção de Alimentos'),
('Allison Da Silva Lima', 'Produção de Alimentos'),
('Maria Claudia Nascimento', 'Produção de Alimentos'),
('Daniel Silva Dos Reis', 'Produção de Alimentos'),
('Shirliany Andrade Do Nascimento', 'Saúde'),
('Igor Araujo Cruz', 'Saúde'),
('Álvaro Leal Da Silva', 'Saúde'),
('Mariane Conceição Paixão', 'Saúde'),
('Leida Maria Rodrigues Do Prado', 'Saúde'),
('Erika De Souza Figueiredo', 'Saúde'),
('Marcos Antonio Pereira Da Silva', 'Saúde'),
('Sabrina Oliveira Campos De Franca', 'Saúde'),
('Jose Otavio Da Silva Junior', 'Saúde'),
('Aparecida Araujo De Freitas', 'Saúde'),
('Gleyciany Goncalves Silva Jesus', 'Saúde'),
('Pedro Henrique Batista Dos Anjos', 'Saúde'),
('Lilian Girardi Miguel Da Silva', 'Saúde'),
('Erica Paulino Da Costa Moreira', 'Saúde'),
('Charles Dikison Souza Guimarães', 'Segurança'),
('Jose Roberto Moraes De Souza', 'Segurança'),
('Leandro Pereira Castro', 'Segurança'),
('Dalva Maria Vitoria De Araujo Carvalho', 'Segurança'),
('Denilson Rodrigues Santana', 'Segurança'),
('Helton Veras Medeiros', 'Segurança'),
('Ruben Gomes De Bastos Prado', 'Tecnologia da Informação'),
('Alisson Ribeiro Da Silva', 'Tecnologia da Informação'),
('Raniere Rodrigues De Oliveira', 'Tecnologia da Informação'),
('Ana Paula Leite Pereira', 'Tecnologia da Informação'),
('Hernande De Castro Coelho', 'Tecnologia da Informação'),
('Alessandro Alves De Vasconcelos', 'Tecnologia da Informação'),
('Sérgio Rodrigues Lima', 'Tecnologia da Informação'),
('Hudson Neves E Silva', 'Tecnologia da Informação'),
('Rafael Do Sacramento Bonfim', 'Tecnologia da Informação'),
('Herminio Jesus Santos Do Carmo', 'Tecnologia da Informação'),
('Joa Victor Ramalho Mendes', 'Tecnologia da Informação'),
('Flippy Maycon Gomes Da Silva', 'Tecnologia da Informação'),
('Adriel Caninde Filgueira Do Amaral', 'Tecnologia da Informação'),
('Douglas Antero Rodrigues Silva', 'Tecnologia da Informação'),
('Lucas Dos Santos Camilo', 'Tecnologia da Informação'),
('Valdiney Marcio De Sousa', 'Tecnologia da Informação'),
('Jose Matheus Alves Do Rosario', 'Tecnologia da Informação'),
('Marcos Alves De Oliveira', 'Tecnologia da Informação'),
('Hudson Andre Vidal Martins', 'Tecnologia da Informação'),
('Kelly Bispo Da Silva', 'Tecnologia da Informação'),
('Leonardo Nemer Afonso', 'Tecnologia da Informação'),
('Marcileide Cardoso De Souza', 'Tecnologia da Informação'),
('Romulo Cesar Silvestre Leite', 'Tecnologia da Informação'),
('Ricardo De Souza Serra', 'Tecnologia da Informação');


-- -----------------------------------------------------
-- Table `instrutores_cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instrutores_cursos` ;
CREATE TABLE IF NOT EXISTS `instrutores_cursos` (
  `id_instrutores_cursos` INT NOT NULL AUTO_INCREMENT,
  `id_instrutores` INT NOT NULL,
  `id_cursos` INT NOT NULL,
  PRIMARY KEY (`id_instrutores_cursos`),
  CONSTRAINT `fk_instrutor_curso_instrutor`
    FOREIGN KEY (`id_instrutores`) REFERENCES `instrutores` (`id_instrutores`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_instrutor_curso_curso`
    FOREIGN KEY (`id_cursos`) REFERENCES `cursos` (`id_cursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  UNIQUE (`id_instrutores`, `id_cursos`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `turmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turmas` ;
CREATE TABLE IF NOT EXISTS `turmas` (
  `id_turmas` INT NOT NULL AUTO_INCREMENT,
  `id_cursos` INT NOT NULL,
  `id_instrutores` INT NULL,
  `codigo_turma` VARCHAR(50) UNIQUE,
  `id_status` INT DEFAULT 1, 
  `id_turno` INT NOT NULL, 
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE, 
  `total_alunos` INT NOT NULL, 
  `alunos_pagantes` INT DEFAULT 0,
  `alunos_bolsistas` INT DEFAULT 0,
  `observacoes` TEXT,
  `eh_hibrida` TINYINT(1) DEFAULT 0 COMMENT '1 se a turma for dividida em 2 salas. Usado na lógica do TEM.',
  
  PRIMARY KEY (`id_turmas`),
  CONSTRAINT `fk_turma_curso`
    FOREIGN KEY (`id_cursos`) REFERENCES `cursos` (`id_cursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_instrutor`
    FOREIGN KEY (`id_instrutores`) REFERENCES `instrutores` (`id_instrutores`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_status`
    FOREIGN KEY (`id_status`) REFERENCES `status_turma` (`id_status`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_turno`
    FOREIGN KEY (`id_turno`) REFERENCES `turno` (`id_turno`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Inserção de dados para `turmas`
-- Usando 1=Manhã, 2=Tarde, 3=Noite, 4=Integral
-- DATAS AJUSTADAS PARA NOVEMBRO/DEZEMBRO DE 2025
INSERT INTO turmas (id_cursos, id_instrutores, codigo_turma, id_status, data_inicio, data_termino, id_turno, total_alunos, alunos_pagantes, alunos_bolsistas, observacoes) VALUES
(1, 1, 'TURMA-2025-001', 1, '2025-11-17', '2025-12-17', 1, 20, 15, 5, 'Turma inicial de Florista'),
(3, 2, 'TURMA-2025-002', 1, '2025-11-03', '2025-12-03', 2, 18, 12, 6, 'Curso Alongamento de Unhas'),
(5, 6, 'TURMA-2025-003', 1, '2025-11-10', '2026-03-10', 3, 25, 20, 5, 'Turma Cabeleireiro - módulo avançado'),
(9, 10, 'TURMA-2025-004', 1, '2025-11-14', '2026-04-14', 1, 30, 25, 5, 'Administrador de Banco de Dados'),
(13, 12, 'TURMA-2025-005', 1, '2025-11-24', '2026-03-24', 2, 15, 10, 5, 'Curso Costureiro'),
(11, 14, 'TURMA-2025-006', 1, '2025-11-28', '2026-04-28', 3, 28, 22, 6, 'Curso Técnico em Redes');

-- -----------------------------------------------------
-- Table `agendamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendamentos` ;
CREATE TABLE IF NOT EXISTS `agendamentos` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `id_turmas` INT NOT NULL,
  `id_salas` INT NOT NULL,
  `id_turno` INT NOT NULL, 
  `data_aula` DATE NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  UNIQUE INDEX `uk_sala_dia` (`id_salas` ASC, `data_aula` ASC),
  UNIQUE INDEX `uk_turma_dia` (`id_turmas` ASC, `data_aula` ASC),
  INDEX `fk_agendamentos_turmas1_idx` (`id_turmas` ASC),
  INDEX `fk_agendamentos_salas1_idx` (`id_salas` ASC),
  CONSTRAINT `fk_agendamentos_turmas1`
    FOREIGN KEY (`id_turmas`)
    REFERENCES `turmas` (`id_turmas`)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamentos_salas1`
    FOREIGN KEY (`id_salas`)
    REFERENCES `salas` (`id_salas`)
    ON DELETE RESTRICT 
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamentos_turno1`
    FOREIGN KEY (`id_turno`) REFERENCES `turno` (`id_turno`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'Armazena cada dia de aula alocada para uma turma em uma sala.';

-- Inserção de dados para `agendamentos`
-- DATAS AJUSTADAS PARA NOVEMBRO/DEZEMBRO DE 2025
INSERT INTO agendamentos (id_turmas, id_salas,id_turno, data_aula) VALUES
(1, 1, 4, '2025-11-17'), -- Seg
(1, 1, 4 ,'2025-11-24'), -- Seg
(2, 12, 4, '2025-11-03'), -- Seg
(2, 12, 4 ,'2025-11-10'), -- Seg
(3, 11, 4 ,'2025-11-10'), -- Seg
(3, 11, 4 ,'2025-11-17'), -- Seg
(4, 7, 4 ,'2025-11-14'), -- Sex
(4, 7, 4 ,'2025-11-21'), -- Sex
(5, 10, 4, '2025-11-24'), -- Seg
(5, 10, 4, '2025-12-01'), -- Seg
(6, 8, 4 ,'2025-11-28'), -- Sex
(6, 8, 4, '2025-12-05'); -- Sex


-- -----------------------------------------------------
-- Table `feriados_recessos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `feriados_recessos`;
CREATE TABLE IF NOT EXISTS `feriados_recessos` (
  `id_feriado` INT NOT NULL AUTO_INCREMENT,
  `data_feriado` DATE NOT NULL UNIQUE,
  `descricao` VARCHAR(255) NOT NULL,
  `fk_id_tipo_feriado` INT NOT NULL, 
  PRIMARY KEY (`id_feriado`),
  CONSTRAINT `fk_feriado_tipo`
    FOREIGN KEY (`fk_id_tipo_feriado`) REFERENCES `tipo_feriado` (`id_tipo_feriado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- Usando 1=feriado, 2=recesso do INSERT INTO tipo_feriado
INSERT INTO feriados_recessos (data_feriado, descricao, fk_id_tipo_feriado) VALUES
-- === FERIADOS OFICIAIS (1) ===
('2025-01-01', 'Confraternização Universal', 1),
('2025-02-25', 'Carnaval', 1),
('2025-02-26', 'Quarta-feira de Cinzas', 1),
('2025-04-18', 'Sexta-feira Santa', 1),
('2025-04-21', 'Tiradentes', 1),
('2025-05-01', 'Dia do Trabalho', 1),
('2025-06-19', 'Corpus Christi', 1),
('2025-09-07', 'Independência do Brasil', 1),
('2025-10-12', 'Nossa Senhora Aparecida', 1),
('2025-11-02', 'Finados', 1),
('2025-11-15', 'Proclamação da República', 1),
('2025-12-25', 'Natal', 1),
('2026-01-01', 'Confraternização Universal', 1),
('2026-02-17', 'Carnaval', 1),
('2026-02-18', 'Quarta-feira de Cinzas', 1),
('2026-02-19', 'Carnaval – ponto facultativo', 1),
('2026-04-03', 'Sexta-feira Santa', 1),
('2026-04-21', 'Tiradentes', 1),
('2026-05-01', 'Dia do Trabalho', 1),
('2026-06-04', 'Corpus Christi', 1),
('2026-07-09', 'Revolução Constitucionalista (SP)', 1),
('2026-09-07', 'Independência do Brasil', 1),
('2026-10-12', 'Nossa Senhora Aparecida', 1),
('2026-10-28', 'Dia do Servidor Público', 1),
('2026-11-02', 'Finados', 1),
('2026-11-15', 'Proclamação da República', 1),
('2026-11-20', 'Dia da Consciência Negra', 1),
('2026-12-25', 'Natal', 1);

-- === PONTES (RECESSO - 2) ===
INSERT INTO feriados_recessos (data_feriado, descricao, fk_id_tipo_feriado) VALUES
('2025-02-28', 'Ponte de Carnaval', 2),
('2025-04-19', 'Ponte Páscoa/Tiradentes', 2),
('2025-06-20', 'Ponte Corpus Christi', 2),
('2025-07-10', 'Recesso Julho', 2),
('2025-10-13', 'Ponte Nossa Senhora Aparecida', 2),
('2025-10-29', 'Ponte Dia do Servidor', 2),
('2025-11-03', 'Ponte Finados', 2),
('2025-11-14', 'Ponte Proclamação da República', 2),
('2025-11-16', 'Recesso Especial', 2),
('2026-02-20', 'Ponte Carnaval', 2),
('2026-04-04', 'Ponte Páscoa/Tiradentes', 2),
('2026-06-05', 'Ponte Corpus Christi', 2);

-- === DIAS NÃO LETIVOS (RECESSO - 2) ===
INSERT INTO feriados_recessos (data_feriado, descricao, fk_id_tipo_feriado) VALUES
('2025-01-02', 'Recesso Escolar', 2),
('2025-01-03', 'Recesso Escolar', 2),
('2025-01-06', 'Recesso Escolar', 2),
('2025-01-07', 'Recesso Escolar', 2),
('2025-01-08', 'Recesso Escolar', 2),
('2025-01-09', 'Recesso Escolar', 2),
('2025-01-10', 'Recesso Escolar', 2),
('2025-01-13', 'Recesso Escolar', 2),
('2025-01-14', 'Recesso Escolar', 2),
('2025-01-15', 'Recesso Escolar', 2),
('2025-01-16', 'Recesso Escolar', 2),
('2025-01-17', 'Recesso Escolar', 2),
('2025-01-20', 'Recesso Escolar', 2),
('2025-01-21', 'Recesso Escolar', 2),
('2025-01-22', 'Recesso Escolar', 2),
('2025-01-23', 'Recesso Escolar', 2),
('2025-01-24', 'Recesso Escolar', 2),
('2025-01-27', 'Recesso Escolar', 2),
('2025-01-28', 'Recesso Escolar', 2),
('2025-01-29', 'Recesso Escolar', 2),
('2025-01-30', 'Recesso Escolar', 2),
('2025-01-31', 'Recesso Escolar', 2),
('2026-01-02', 'Recesso Escolar', 2),
('2026-01-05', 'Recesso Escolar', 2),
('2026-01-06', 'Recesso Escolar', 2),
('2026-01-07', 'Recesso Escolar', 2),
('2026-01-08', 'Recesso Escolar', 2),
('2026-01-09', 'Recesso Escolar', 2),
('2026-01-12', 'Recesso Escolar', 2),
('2026-01-13', 'Recesso Escolar', 2),
('2026-01-14', 'Recesso Escolar', 2),
('2026-01-15', 'Recesso Escolar', 2),
('2026-01-16', 'Recesso Escolar', 2),
('2026-01-19', 'Recesso Escolar', 2),
('2026-01-20', 'Recesso Escolar', 2),
('2026-01-21', 'Recesso Escolar', 2),
('2026-01-22', 'Recesso Escolar', 2),
('2026-01-23', 'Recesso Escolar', 2),
('2026-01-26', 'Recesso Escolar', 2),
('2026-01-27', 'Recesso Escolar', 2),
('2026-01-28', 'Recesso Escolar', 2),
('2026-01-29', 'Recesso Escolar', 2),
('2026-01-30', 'Recesso Escolar', 2),
('2026-02-02', 'Recesso Escolar', 2),
('2026-02-03', 'Recesso Escolar', 2),
('2026-02-04', 'Recesso Escolar', 2),
('2026-02-05', 'Recesso Escolar', 2),
('2026-02-06', 'Recesso Escolar', 2),
('2026-02-09', 'Recesso Escolar', 2),
('2026-02-10', 'Recesso Escolar', 2),
('2026-02-11', 'Recesso Escolar', 2),
('2026-02-12', 'Recesso Escolar', 2),
('2026-02-13', 'Recesso Escolar', 2);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;