-- MySQL Script generated by MySQL Workbench
-- Adaptado para phpMyAdmin
-- Data: 2025-08-23

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgst_bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sgst_bd` ;
CREATE SCHEMA IF NOT EXISTS `sgst_bd` DEFAULT CHARACTER SET utf8 ;
USE `sgst_bd` ;

-- -----------------------------------------------------
-- Table `tipos_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipos_sala` ;
CREATE TABLE IF NOT EXISTS `tipos_sala` (
  `idTipo_sala` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` VARCHAR(100) NOT NULL UNIQUE,
  PRIMARY KEY (`idTipo_sala`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `tipos_sala`
--

INSERT INTO tipos_sala (nome_tipo) VALUES
('Sala de aula Inovadora'),
('Laboratório de TI'),
('Laboratório de Moda'),
('Laboratório de Imagem Pessoal'),
('Auditório'),
('Laboratório Multiuso');

-- -----------------------------------------------------
-- Table `salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salas` ;
CREATE TABLE IF NOT EXISTS `salas` (
  `id_salas` INT NOT NULL AUTO_INCREMENT,
  `nome_sala` VARCHAR(100) NOT NULL,
  `capacidade_maxima` INT NOT NULL,
  `idTipo_sala` INT,
  `local` VARCHAR(255),
  `recursos_especiais` TEXT,
  PRIMARY KEY (`id_salas`),
  CONSTRAINT `fk_sala_tipo`
    FOREIGN KEY (`idTipo_sala`) REFERENCES `tipos_sala` (`idTipo_sala`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--
-- Despejando dados para a tabela `salas`
--

INSERT INTO salas (nome_sala, capacidade_maxima, idTipo_sala, local, recursos_especiais) VALUES
('Inovadora 1', 30, 1, 'Cep Talal Abu Allan', '1º Andar, carteiras universitárias, TV ou projetor, lousa digital ou quadro branco, acesso à internet, tomadas para notebooks, iluminação adequada, climatização, espaço para dinâmicas, decoração moderna, recursos multimídia, ambiente colaborativo'),
('Inovadora 2', 20, 1, 'Cep Talal Abu Allan', '2º Andar, mesas móveis formato trapézio, TV ou projetor, lousa digital ou quadro branco, internet, tomadas, climatização, recursos multimídia'),
('Inovadora 3', 35, 1, 'Cep Talal Abu Allan', '2º Andar, carteiras universitárias, TV ou projetor, lousa digital, internet, climatização, recursos multimídia'),
('Inovadora 4', 33, 1, 'Cep Talal Abu Allan', '2º Andar, carteiras universitárias, TV ou projetor, lousa digital, internet, climatização'),
('Inovadora 5', 20, 1, 'Cep Talal Abu Allan', '2º Andar, mesas móveis formato trapézio, TV ou projetor, internet, climatização'),
('Inovadora 6', 32, 1, 'Cep Talal Abu Allan', '2º Andar, carteiras universitárias, TV ou projetor, internet, climatização'),
('Técnico de Sistemas e Rede 1', 28, 2, 'Cep Talal Abu Allan', 'rack de rede, switches, cabeamento estruturado, roteadores, 30 computadores, servidor, projetor multimídia, nobreak'),
('Técnico de Sistemas e Rede 2', 28, 2, 'Cep Talal Abu Allan', 'rack de rede, switches, cabeamento estruturado, roteadores, 30 computadores, servidor, projetor multimídia, nobreak'),
('Técnico de Sistemas', 30, 2, 'Cep Talal Abu Allan', '30 computadores, servidor local, projetor multimídia, softwares de programação, banco de dados, nobreak'),
('Produção de Moda', 20, 3, 'Cep Talal Abu Allan', 'máquinas de costura, overlock, mesa de corte, manequins, ferro, iluminação, armários para tecidos, kits de modelagem'),
('Imagem - Cabelos', 18, 4, 'Cep Talal Abu Allan', 'cadeiras de cabeleireiro, lavatórios, espelhos, secadores, chapinhas, iluminação adequada'),
('Imagem - Estética e Unhas', 16, 4, 'Cep Talal Abu Allan', 'macas reclináveis, mesas de manicure, esterilizadores, equipamentos de estética, poltronas de pedicure'),
('Imagem - Maquiagem e Produção', 14, 4, 'Cep Talal Abu Allan', 'cadeiras de maquiagem, bancadas com espelhos, iluminação de camarim, tomadas, kits de pincéis'),
('Auditório', 70, 5, 'Cep Talal Abu Allan', 'projetor, som, ar-condicionado, 70 cadeiras, iluminação adequada'),
('Técnico de Sistemas 1', 30, 2, 'Polo Recanto da Emas', 'computadores, servidor local, projetor multimídia, softwares de programação'),
('Técnico de Sistemas 2', 30, 2, 'Polo Recanto da Emas', 'computadores, servidor local, projetor multimídia, softwares de programação'),
('Multiuso de Cabelo, Unhas e Moda', 16, 6, 'Polo Recanto da Emas', 'máquinas de costura, secador, TV 85", bancadas, espelhos, cadeiras, lavatórios, iluminação estética');

-- -----------------------------------------------------
-- Table `cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cursos` ;
CREATE TABLE IF NOT EXISTS `cursos` (
  `id_cursos` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(255) NOT NULL,
  `carga_horaria` INT NOT NULL,
  `necessidade_sala` VARCHAR(255),
  PRIMARY KEY (`id_cursos`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `cursos`
--

INSERT INTO cursos (nome_curso, carga_horaria, necessidade_sala) VALUES
('Florista', 160, 'Sala de aula Inovadora'),
('Fotografia comercial com celular', 36, 'Sala de aula Inovadora'),
('Alongamento de Unhas', 60, 'Imagem - Estética e Unhas'),
('Barbeiro', 172, 'Imagem - Cabelos'),
('Cabeleireiro', 400, 'Imagem - Cabelos'),
('Depilador', 160, 'Imagem - Estética e Unhas'),
('Manicure e Pedicure', 160, 'Imagem - Estética e Unhas'),
('Maquiador', 160, 'Imagem - Cabelos'),
('Administrador de Banco de Dados', 200, 'Laboratório de TI'),
('Desenvolvedor Back-end', 500, 'Laboratório de TI'),
('Técnico em Redes de Computadores', 1000, 'Laboratório de TI'),
('Aperfeiçoamento em Corte e Costura', 60, 'Laboratório de Moda'),
('Costureiro', 212, 'Laboratório de Moda'),
('Estilista de Moda', 408, 'Laboratório de Moda');

-- -----------------------------------------------------
-- Table `instrutores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instrutores` ;
CREATE TABLE IF NOT EXISTS `instrutores` (
  `id_instrutores` INT NOT NULL AUTO_INCREMENT,
  `nome_instrutor` VARCHAR(100) NOT NULL UNIQUE,
  `segmento_principal` VARCHAR(100),
  `habilidades_extras` TEXT,
  PRIMARY KEY (`id_instrutores`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `isntrutores`
--

INSERT INTO instrutores (nome_instrutor, segmento_principal) VALUES
('Luzia Pereira De Andrade', 'Beleza'),
('Stephanie Lopes De Sousa', 'Beleza'),
('Maria Auxiliadora De Almeida Rodrigues', 'Beleza'),
('Maria Edinalda Pinheiro Da Silva', 'Beleza'),
('Caroline Manso Da Costa Silva', 'Beleza'),
('Thiago Augusto Ferreira', 'Beleza'),
('Adriano Da Silva Santos', 'Beleza'),
('Jarlane Carneiro De Lima Pereira', 'Beleza'),
('Camila Marques Pereira', 'Beleza'),
('Mário Carvalho De Sousa Baldez', 'Beleza'),
('Mônica Rodrigues Da Costa Araújo', 'Beleza'),
('João De Deus Meira', 'Beleza'),
('Rubia Martins De Melo', 'Beleza'),
('Thiago De Sousa Costa', 'Beleza'),
('David Da Silva Prado', 'Beleza'),
('Daniele Moraes De Oliveira Ferreira Siqueira', 'Beleza'),
('Wesley Lima Da Nóbrega', 'Comunicação'),
('Arthur Gramacho Dos Santos', 'Comunicação'),
('Juliana Mendes De Brito', 'Educacional'),
('Bruna Gomes De Moura Medeiros', 'Educacional');


-- -----------------------------------------------------
-- Table `turmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `turmas` ;
CREATE TABLE IF NOT EXISTS `turmas` (
  `id_turmas` INT NOT NULL AUTO_INCREMENT,
  `id_cursos` INT NOT NULL,
  `id_instrutores` INT NULL,
  `codigo_turma` VARCHAR(50) UNIQUE,
  `status` VARCHAR(50) DEFAULT 'Planejada',
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE,
  `turno` VARCHAR(50),
  `total_alunos` INT,
  `alunos_pagantes` INT,
  `alunos_bolsistas` INT,
  `observacoes` TEXT,
  PRIMARY KEY (`id_turmas`),
  CONSTRAINT `fk_turma_curso`
    FOREIGN KEY (`id_cursos`) REFERENCES `cursos` (`id_cursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_turma_instrutor`
    FOREIGN KEY (`id_instrutores`) REFERENCES `instrutores` (`id_instrutores`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `turmas`
--

INSERT INTO turmas (id_cursos, id_instrutores, codigo_turma, status, data_inicio, data_termino, turno, total_alunos, alunos_pagantes, alunos_bolsistas, observacoes) VALUES
(1, 1, 'TURMA-2025-001', 'Planejada', '2025-09-15', '2025-11-15', 'Manhã', 20, 15, 5, 'Turma inicial de Florista'),
(3, 2, 'TURMA-2025-002', 'Planejada', '2025-10-01', '2025-12-01', 'Tarde', 18, 12, 6, 'Curso Alongamento de Unhas'),
(5, 6, 'TURMA-2025-003', 'Planejada', '2025-09-20', '2026-01-20', 'Noite', 25, 20, 5, 'Turma Cabeleireiro - módulo avançado'),
(9, 10, 'TURMA-2025-004', 'Planejada', '2025-09-25', '2026-02-25', 'Manhã', 30, 25, 5, 'Administrador de Banco de Dados'),
(13, 12, 'TURMA-2025-005', 'Planejada', '2025-10-05', '2026-02-05', 'Tarde', 15, 10, 5, 'Curso Costureiro'),
(11, 14, 'TURMA-2025-006', 'Planejada', '2025-10-10', '2026-03-10', 'Noite', 28, 22, 6, 'Curso Técnico em Redes');

-- -----------------------------------------------------
-- Table `agendamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agendamentos` ;
CREATE TABLE IF NOT EXISTS `agendamentos` (
  `id_agendamentos` INT NOT NULL AUTO_INCREMENT,
  `id_turmas` INT NOT NULL,
  `id_salas` INT NOT NULL,
  `data_aula` DATE NOT NULL,
  `turno` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_agendamentos`),
  CONSTRAINT `fk_agendamento_turma`
    FOREIGN KEY (`id_turmas`) REFERENCES `turmas` (`id_turmas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_sala`
    FOREIGN KEY (`id_salas`) REFERENCES `salas` (`id_salas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Despejando dados para a tabela `agendamentos`
--

INSERT INTO agendamentos (id_turmas, id_salas, data_aula, turno) VALUES
(1, 1, '2025-09-15', 'Manhã'),
(1, 1, '2025-09-22', 'Manhã'),
(2, 12, '2025-10-01', 'Tarde'),
(2, 12, '2025-10-08', 'Tarde'),
(3, 11, '2025-09-20', 'Noite'),
(3, 11, '2025-09-27', 'Noite'),
(4, 7, '2025-09-25', 'Manhã'),
(4, 7, '2025-10-02', 'Manhã'),
(5, 10, '2025-10-05', 'Tarde'),
(5, 10, '2025-10-12', 'Tarde'),
(6, 8, '2025-10-10', 'Noite'),
(6, 8, '2025-10-17', 'Noite');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;